pipeline {
    agent {
        docker {
            image 'maven:3.8.3-openjdk-17'
            reuseNode true
            registryUrl 'https://index.docker.io/v1/'
            registryCredentialsId 'docker-hub'
        }
    }
    environment {
        GC = credentials('github-spring-cicd') // 생성해야 합니다.
    }
    triggers {
        githubPush()
    }
    stages {
        stage('maven build, test, packageing(war)') {
            steps {
                sh 'mvn clean install'
            }
        }
    }
}
